/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosElementoCoalescenteHidrofobicoNbf10ppRouteImport } from './routes/produtos.elemento-coalescente-hidrofobico-nbf-10pp'
import { Route as ProdutosCaixaSeparadoraAguaOleoRouteImport } from './routes/produtos.caixa-separadora-agua-oleo'
import { Route as ProdutosSlugRouteImport } from './routes/produtos.$slug'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosElementoCoalescenteHidrofobicoNbf10ppRoute =
  ProdutosElementoCoalescenteHidrofobicoNbf10ppRouteImport.update({
    id: '/elemento-coalescente-hidrofobico-nbf-10pp',
    path: '/elemento-coalescente-hidrofobico-nbf-10pp',
    getParentRoute: () => ProdutosRoute,
  } as any)
const ProdutosCaixaSeparadoraAguaOleoRoute =
  ProdutosCaixaSeparadoraAguaOleoRouteImport.update({
    id: '/caixa-separadora-agua-oleo',
    path: '/caixa-separadora-agua-oleo',
    getParentRoute: () => ProdutosRoute,
  } as any)
const ProdutosSlugRoute = ProdutosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProdutosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/caixa-separadora-agua-oleo': typeof ProdutosCaixaSeparadoraAguaOleoRoute
  '/produtos/elemento-coalescente-hidrofobico-nbf-10pp': typeof ProdutosElementoCoalescenteHidrofobicoNbf10ppRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/caixa-separadora-agua-oleo': typeof ProdutosCaixaSeparadoraAguaOleoRoute
  '/produtos/elemento-coalescente-hidrofobico-nbf-10pp': typeof ProdutosElementoCoalescenteHidrofobicoNbf10ppRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/produtos': typeof ProdutosRouteWithChildren
  '/sobre': typeof SobreRoute
  '/produtos/$slug': typeof ProdutosSlugRoute
  '/produtos/caixa-separadora-agua-oleo': typeof ProdutosCaixaSeparadoraAguaOleoRoute
  '/produtos/elemento-coalescente-hidrofobico-nbf-10pp': typeof ProdutosElementoCoalescenteHidrofobicoNbf10ppRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/produtos'
    | '/sobre'
    | '/produtos/$slug'
    | '/produtos/caixa-separadora-agua-oleo'
    | '/produtos/elemento-coalescente-hidrofobico-nbf-10pp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/produtos'
    | '/sobre'
    | '/produtos/$slug'
    | '/produtos/caixa-separadora-agua-oleo'
    | '/produtos/elemento-coalescente-hidrofobico-nbf-10pp'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/produtos'
    | '/sobre'
    | '/produtos/$slug'
    | '/produtos/caixa-separadora-agua-oleo'
    | '/produtos/elemento-coalescente-hidrofobico-nbf-10pp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  ProdutosRoute: typeof ProdutosRouteWithChildren
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos/elemento-coalescente-hidrofobico-nbf-10pp': {
      id: '/produtos/elemento-coalescente-hidrofobico-nbf-10pp'
      path: '/elemento-coalescente-hidrofobico-nbf-10pp'
      fullPath: '/produtos/elemento-coalescente-hidrofobico-nbf-10pp'
      preLoaderRoute: typeof ProdutosElementoCoalescenteHidrofobicoNbf10ppRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/produtos/caixa-separadora-agua-oleo': {
      id: '/produtos/caixa-separadora-agua-oleo'
      path: '/caixa-separadora-agua-oleo'
      fullPath: '/produtos/caixa-separadora-agua-oleo'
      preLoaderRoute: typeof ProdutosCaixaSeparadoraAguaOleoRouteImport
      parentRoute: typeof ProdutosRoute
    }
    '/produtos/$slug': {
      id: '/produtos/$slug'
      path: '/$slug'
      fullPath: '/produtos/$slug'
      preLoaderRoute: typeof ProdutosSlugRouteImport
      parentRoute: typeof ProdutosRoute
    }
  }
}

interface ProdutosRouteChildren {
  ProdutosSlugRoute: typeof ProdutosSlugRoute
  ProdutosCaixaSeparadoraAguaOleoRoute: typeof ProdutosCaixaSeparadoraAguaOleoRoute
  ProdutosElementoCoalescenteHidrofobicoNbf10ppRoute: typeof ProdutosElementoCoalescenteHidrofobicoNbf10ppRoute
}

const ProdutosRouteChildren: ProdutosRouteChildren = {
  ProdutosSlugRoute: ProdutosSlugRoute,
  ProdutosCaixaSeparadoraAguaOleoRoute: ProdutosCaixaSeparadoraAguaOleoRoute,
  ProdutosElementoCoalescenteHidrofobicoNbf10ppRoute:
    ProdutosElementoCoalescenteHidrofobicoNbf10ppRoute,
}

const ProdutosRouteWithChildren = ProdutosRoute._addFileChildren(
  ProdutosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  ProdutosRoute: ProdutosRouteWithChildren,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
